<?php

declare(strict_types=1);

// Real book data + cover images sourced from workshops-de/bookmonkey-api (v4.2.0),
// the reference dataset for the Bookmonkey workshop app: https://github.com/workshops-de/bookmonkey-api
// Cover images are shipped locally in public/covers and served by this backend.

$dbPath = __DIR__ . '/bookmonkey.sqlite';

$pdo = new PDO('sqlite:' . $dbPath);
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$pdo->exec(file_get_contents(__DIR__ . '/schema.sql'));

$count = (int) $pdo->query('SELECT COUNT(*) FROM books')->fetchColumn();
if ($count > 0) {
    echo "Database already seeded ({$count} books). Skipping.\n";
    exit(0);
}

$books = [
    ['9780747532699', 'Harry Potter and the Philosopher’s Stone', null, 'J. K. Rowling', 'Bloomsbury', 223, '12.99', '/covers/9780747532699.png', 'Harry Potter has never heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment, they are swiftly confiscated by his aunt and uncle. Then, on Harry’s eleventh birthday, a giant of a man bursts in with news: Harry is a wizard, and a place awaits him at Hogwarts School of Witchcraft and Wizardry.', 1],
    ['9780747538493', 'Harry Potter and the Chamber of Secrets', null, 'J. K. Rowling', 'Bloomsbury', 251, '12.99', '/covers/9780747538493.png', 'Harry Potter’s summer with the Dursleys has been awful. He is counting the days back to Hogwarts when a warning from a house-elf named Dobby comes true and the Chamber of Secrets is opened once more – unleashing a monster that petrifies the school’s pupils one by one.', 1],
    ['9780747542155', 'Harry Potter and the Prisoner of Azkaban', null, 'J. K. Rowling', 'Bloomsbury', 317, '13.99', '/covers/9780747542155.png', 'When the Knight Bus crashes through the darkness and screeches to a halt in front of him, it is the start of another far-from-ordinary year at Hogwarts for Harry Potter. Sirius Black, escaped mass-murderer and follower of Lord Voldemort, is on the loose – and they say he is coming after Harry.', 1],
    ['9780747546245', 'Harry Potter and the Goblet of Fire', null, 'J. K. Rowling', 'Bloomsbury', 636, '16.99', '/covers/9780747546245.png', 'The Triwizard Tournament is to be held at Hogwarts. Only wizards who are over seventeen are allowed to enter – but that doesn’t stop Harry dreaming that he will win the competition. Then at Hallowe’en, when the Goblet of Fire makes its selection, Harry is amazed to find his name is one of those that the magical cup picks out.', 1],
    ['9780747551003', 'Harry Potter and the Order of the Phoenix', null, 'J. K. Rowling', 'Bloomsbury', 766, '18.99', '/covers/9780747551003.png', 'Dark times have come to Hogwarts. After the Dementors’ attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him. There are many who deny the Dark Lord’s return, but Harry is not alone: a secret order gathers at Grimmauld Place to fight against the Dark forces.', 1],
    ['9780747581086', 'Harry Potter and the Half-Blood Prince', null, 'J. K. Rowling', 'Bloomsbury', 607, '17.99', '/covers/9780747581086.png', 'When Dumbledore arrives at Privet Drive one summer night to collect Harry Potter, his wand hand is blackened and shrivelled, but he does not reveal why. Meanwhile, for the first time in living memory, Hogwarts has a new Potions master and Harry finds an old book annotated by a mysterious Half-Blood Prince.', 1],
    ['9780747591054', 'Harry Potter and the Deathly Hallows', null, 'J. K. Rowling', 'Bloomsbury', 607, '19.99', '/covers/9780747591054.png', 'As he climbs into the sidecar of Hagrid’s motorbike and takes to the skies, leaving Privet Drive for the last time, Harry Potter knows that Lord Voldemort and the Death Eaters are close behind. The protective charm that has kept him safe until now is broken, and the final battle must begin.', 1],
    ['9780553588484', 'A Game of Thrones', 'A Song of Ice and Fire, Book One', 'George R. R. Martin', 'Bantam Books', 835, '14.99', '/covers/9780553588484.png', 'In the game of thrones, you win or you die. Long ago, in a time forgotten, a preternatural event threw the seasons out of balance. Now, as winter approaches again, the noble houses of the Seven Kingdoms are drawn into a web of alliance and conflict from the frozen Wall in the north to the sun-drenched south.', 1],
    ['9780553579901', 'A Clash of Kings', 'A Song of Ice and Fire, Book Two', 'George R. R. Martin', 'Bantam Books', 761, '14.99', '/covers/9780553579901.png', 'A comet the colour of blood and flame cuts across the sky. Six factions vie for control of a divided land, and the Iron Throne of the Seven Kingdoms awaits the winner. Through it all, the Stark children scatter across a war-torn continent while an exiled queen nurtures three young dragons.', 1],
    ['9780553573428', 'A Storm of Swords', 'A Song of Ice and Fire, Book Three', 'George R. R. Martin', 'Bantam Books', 973, '15.99', '/covers/9780553573428.png', 'Of the five contenders for power, one is dead, one is in disfavour, and still the wars rage. Amid the chaos, Jon Snow rises among the Night’s Watch, Robb Stark wins battle after battle, and Daenerys Targaryen frees a city of slaves – but every triumph carries a terrible price.', 1],
    ['9780553582024', 'A Feast for Crows', 'A Song of Ice and Fire, Book Four', 'George R. R. Martin', 'Bantam Books', 1060, '15.99', '/covers/9780553582024.png', 'The war in the Seven Kingdoms has burned itself out, but its survivors emerge into a changed landscape of ruined castles and unquiet dead. In the north, Cersei Lannister rules an uneasy regency, while in the Riverlands the smallfolk pick over the bones of the fallen.', 1],
    ['9780553385953', 'A Dance with Dragons', 'A Song of Ice and Fire, Book Five', 'George R. R. Martin', 'Bantam Books', 1056, '16.99', '/covers/9780553385953.png', 'In the aftermath of a colossal battle, Daenerys Targaryen rules Meereen as queen of a city built on dust and death, beset by enemies. Far away, Tyrion Lannister has escaped King’s Landing with a price on his head, and at the Wall Jon Snow faces the fury of a betrayed people.', 1],
    ['9780547928210', 'The Fellowship of the Ring', 'The Lord of the Rings, Part One', 'J. R. R. Tolkien', 'Houghton Mifflin', 423, '15.99', '/covers/9780547928210.png', 'In a sleepy village in the Shire, a young hobbit is entrusted with an immense task. He must make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ruling Ring of Power – the only thing that prevents the Dark Lord Sauron’s dominion.', 1],
    ['9780547928203', 'The Two Towers', 'The Lord of the Rings, Part Two', 'J. R. R. Tolkien', 'Houghton Mifflin', 352, '15.99', '/covers/9780547928203.png', 'The Fellowship is scattered. Some are bracing hopelessly for war against the ancient evil of Mordor; others are contending with the treachery of the wizard Saruman. Frodo and Sam, meanwhile, are journeying into the very heart of the Shadow, guided by the treacherous Gollum.', 1],
    ['9780547928197', 'The Return of the King', 'The Lord of the Rings, Part Three', 'J. R. R. Tolkien', 'Houghton Mifflin', 416, '15.99', '/covers/9780547928197.png', 'The armies of the Dark Lord are massing as his evil shadow spreads ever wider. Men, dwarves, elves and ents unite forces to do battle against the Dark. Meanwhile, Frodo and Sam struggle towards Mount Doom, the last stage of their journey to destroy the Ring of Power.', 1],
    ['9781338635171', 'The Ballad of Songbirds and Snakes', 'A Hunger Games Novel', 'Suzanne Collins', 'Scholastic Press', 528, '16.99', '/covers/9781338635171.png', 'It is the morning of the reaping that will kick off the tenth annual Hunger Games. In the Capitol, eighteen-year-old Coriolanus Snow is preparing for his one shot at glory as a mentor in the Games. The odds are against him: he has been given the humiliating assignment of mentoring the girl tribute from impoverished District 12.', 1],
    ['9780439023481', 'The Hunger Games', null, 'Suzanne Collins', 'Scholastic Press', 374, '12.99', '/covers/9780439023481.png', 'In the ruins of a place once known as North America lies the nation of Panem. The Capitol keeps the twelve districts in line by forcing them to send one boy and one girl to fight to the death in a televised Hunger Games. When her little sister is chosen, sixteen-year-old Katniss Everdeen volunteers to take her place.', 1],
    ['9780439023498', 'Catching Fire', null, 'Suzanne Collins', 'Scholastic Press', 391, '12.99', '/covers/9780439023498.png', 'Katniss Everdeen has survived the Hunger Games twice, but she has angered the Capitol by defying its rules. Now, as the districts stir with the first sparks of rebellion, President Snow makes it clear that the price of her survival – and her family’s – is very high indeed.', 1],
    ['9780439023511', 'Mockingjay', null, 'Suzanne Collins', 'Scholastic Press', 390, '12.99', '/covers/9780439023511.png', 'Katniss Everdeen has survived the arena twice, but nothing is safe. The Capitol wants revenge, and the rebels of District 13 want Katniss to become the Mockingjay – the symbol of their revolution – whatever the personal cost.', 1],
    ['9780812511819', 'The Eye of the World', 'The Wheel of Time, Book One', 'Robert Jordan', 'Tor Books', 814, '14.99', '/covers/9780812511819.png', 'The Wheel of Time turns and Ages come and pass. When the village of Emond’s Field is attacked by monstrous Trollocs, three young men flee into a wider world with the Aes Sedai Moiraine, who tells them that one of them may be the Dragon Reborn – the champion prophesied to save the world, or break it.', 1],
    ['9780812517729', 'The Great Hunt', 'The Wheel of Time, Book Two', 'Robert Jordan', 'Tor Books', 705, '14.99', '/covers/9780812517729.png', 'Rand al’Thor has been proclaimed neither Aes Sedai nor Warder, and yet he can channel the One Power. Now he must ride in pursuit of the stolen Horn of Valere, an artefact that can call dead heroes back from the grave to fight in the Last Battle.', 1],
    ['9780812513714', 'The Dragon Reborn', 'The Wheel of Time, Book Three', 'Robert Jordan', 'Tor Books', 675, '14.99', '/covers/9780812513714.png', 'Rand al’Thor has fled from those who would call him the Dragon Reborn, but the Pattern weaves on. Drawn towards the city of Tear and the sword Callandor, which only the true Dragon can wield, Rand must decide whether to embrace the destiny the world has thrust upon him.', 1],
    ['9780812513738', 'The Shadow Rising', 'The Wheel of Time, Book Four', 'Robert Jordan', 'Tor Books', 981, '15.99', '/covers/9780812513738.png', 'The seals of Shayol Ghul are weakening, and the Forsaken are loose upon the world. Rand al’Thor journeys into the Aiel Waste to learn the secret history of a proud desert people, while in the White Tower a hidden enemy moves against the Amyrlin Seat.', 1],
    ['9780812550306', 'The Fires of Heaven', 'The Wheel of Time, Book Five', 'Robert Jordan', 'Tor Books', 963, '15.99', '/covers/9780812550306.png', 'Prophecy is being fulfilled as Rand al’Thor leads the Aiel out of the Three-fold Land, but the way is barred by the renegade Couladin and by the Forsaken Rahvin, who has seized power in Andor. Meanwhile Nynaeve and Elayne hunt the Black Ajah across the nations.', 1],
    ['9780765350381', 'Mistborn: The Final Empire', null, 'Brandon Sanderson', 'Tor Books', 541, '13.99', '/covers/9780765350381.png', 'For a thousand years the ash fell and no flowers bloomed. For a thousand years the Skaa slaved in misery and lived in fear while the Lord Ruler reigned with absolute power. Then a half-Skaa street urchin named Vin discovers she can wield the magic of Allomancy – and a notorious crew of thieves plans the ultimate heist.', 1],
    ['9780765356130', 'Mistborn: The Well of Ascension', null, 'Brandon Sanderson', 'Tor Books', 590, '13.99', '/covers/9780765356130.png', 'The Lord Ruler is dead, and the impossible has been accomplished. But now Vin and Elend must contend with the chaos left behind: three armies besiege their city, a mysterious mist-spirit stalks Vin, and the power hidden in the Well of Ascension may be the world’s only hope – or its doom.', 1],
    ['9780765356147', 'Mistborn: The Hero of Ages', null, 'Brandon Sanderson', 'Tor Books', 572, '13.99', '/covers/9780765356147.png', 'The ash falls ever harder, the mists kill, and the world slowly dies. Vin and Elend have discovered the secret at the heart of the Lord Ruler’s empire, but releasing the force imprisoned in the Well of Ascension may have doomed them all. Now the hunt for the hoards of the Lord Ruler is the last hope.', 1],
    ['9780756404741', 'The Name of the Wind', 'The Kingkiller Chronicle: Day One', 'Patrick Rothfuss', 'DAW Books', 662, '14.99', '/covers/9780756404741.png', 'Told in Kvothe’s own voice, this is the tale of the magically gifted young man who grows to be the most notorious wizard his world has ever seen. From his childhood in a troupe of traveling players to his years spent as a near-feral orphan in a crime-ridden city, this is a masterpiece of storytelling.', 1],
    ['9780756407919', 'The Wise Man’s Fear', 'The Kingkiller Chronicle: Day Two', 'Patrick Rothfuss', 'DAW Books', 994, '15.99', '/covers/9780756407919.png', 'Kvothe continues the story of his life, recounting how he leaves the University to seek his fortune abroad. He crosses swords with a legendary assassin, learns the intricacies of the Fae realm, and inches ever closer to the truth about the Chandrian who murdered his family.', 1],
    ['9780679879244', 'The Golden Compass', 'His Dark Materials, Book One', 'Philip Pullman', 'Alfred A. Knopf', 399, '12.99', '/covers/9780679879244.png', 'Lyra Belacqua and her daemon Pantalaimon live half-wild in the corridors of Jordan College, Oxford. When children begin to vanish, taken by the sinister Gobblers, Lyra travels north to a land of armoured bears and witch-clans to rescue her friend – and stumbles into a war that spans worlds.', 1],
    ['9780679879251', 'The Subtle Knife', 'His Dark Materials, Book Two', 'Philip Pullman', 'Alfred A. Knopf', 326, '12.99', '/covers/9780679879251.png', 'In a sun-scorched, deserted city between the worlds, Lyra meets Will, a boy fleeing a killing. Together they find the subtle knife, a blade that can cut windows between universes – and become the most-wanted fugitives in every world they enter.', 1],
    ['9780679879268', 'The Amber Spyglass', 'His Dark Materials, Book Three', 'Philip Pullman', 'Alfred A. Knopf', 518, '13.99', '/covers/9780679879268.png', 'Will and Lyra, whose fates are bound together, are drawn into a war of cosmic scale: the Authority’s forces gather, an ex-nun builds a spyglass that reveals the elusive Dust, and the two children must journey even to the land of the dead to set the universe right.', 1],
    ['9780064404990', 'The Lion, the Witch and the Wardrobe', null, 'C. S. Lewis', 'HarperCollins', 206, '8.99', '/covers/9780064404990.png', 'Four siblings step through the back of a wardrobe into the frozen land of Narnia, held a hundred years in winter by the White Witch. With the great lion Aslan on the move, Lucy, Edmund, Susan and Peter are caught up in a battle to free Narnia from the Witch’s spell.', 1],
    ['9780064405010', 'Prince Caspian', 'The Return to Narnia', 'C. S. Lewis', 'HarperCollins', 223, '8.99', '/covers/9780064405010.png', 'The Pevensie children are pulled back into Narnia to find that centuries have passed and their beloved land is oppressed by the Telmarines. Prince Caspian, the rightful king, has blown Susan’s magic horn, and a war for the soul of Narnia begins.', 1],
    ['9780064405027', 'The Voyage of the Dawn Treader', null, 'C. S. Lewis', 'HarperCollins', 271, '8.99', '/covers/9780064405027.png', 'Lucy and Edmund, along with their odious cousin Eustace, are swallowed into a painting and onto the deck of the Dawn Treader. King Caspian is sailing to the end of the world in search of seven lost lords – and the very edge of Aslan’s country.', 1],
    ['9780786838653', 'The Lightning Thief', null, 'Rick Riordan', 'Disney-Hyperion', 377, '9.99', '/covers/9780786838653.png', 'Twelve-year-old Percy Jackson is on the most dangerous quest of his life. With the help of a satyr and a daughter of Athena, Percy must journey across the United States to catch a thief who has stolen the original weapon of mass destruction – Zeus’s master bolt.', 1],
    ['9780786856855', 'The Sea of Monsters', null, 'Rick Riordan', 'Disney-Hyperion', 279, '9.99', '/covers/9780786856855.png', 'After a summer spent trying to prevent a catastrophic war among the Greek gods, Percy Jackson finds his mission at Camp Half-Blood interrupted by bad news: the magical borders that protect the camp are failing, and only the Golden Fleece can save it.', 1],
    ['9781423101451', 'The Titan’s Curse', null, 'Rick Riordan', 'Disney-Hyperion', 312, '9.99', '/covers/9781423101451.png', 'When the goddess Artemis goes missing, she is believed to have been kidnapped. Now there is only one way to find her, and a prophecy that leads Percy and his friends on a desperate cross-country rescue against a rising army of monsters.', 1],
    ['9780441172719', 'Dune', null, 'Frank Herbert', 'Ace Books', 604, '13.99', '/covers/9780441172719.png', 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the spice melange. When treachery destroys his house, Paul is driven into the deep desert and a destiny greater than he could have imagined.', 1],
    ['9780441172696', 'Dune Messiah', null, 'Frank Herbert', 'Ace Books', 331, '12.99', '/covers/9780441172696.png', 'Twelve years after his victory over House Harkonnen, Paul Atreides rules as emperor and reluctant god, his jihad having claimed sixty billion lives. Now a web of conspiracy – spun by a Guild navigator, a Bene Gesserit, a Tleilaxu Face Dancer and Paul’s own sister – tightens around the throne.', 1],
    ['9780547928227', 'The Hobbit', 'or There and Back Again', 'J. R. R. Tolkien', 'Houghton Mifflin', 300, '13.99', '/covers/9780547928227.png', 'Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely travelling further than the pantry of his hobbit-hole. But his contentment is disturbed when the wizard Gandalf and a company of thirteen dwarves arrive to whisk him away on an adventure to reclaim a stolen treasure guarded by the dragon Smaug.', 1],
    ['9781583335086', 'The Willpower Instinct', 'How Self-Control Works, Why It Matters, and What You Can Do to Get More of It', 'Kelly McGonigal', 'Avery', 275, '17', '/covers/9781583335086.png', 'Drawing on the latest research and the practical wisdom of her hugely popular Stanford course, health psychologist Kelly McGonigal explains what willpower is, how it works, and why it matters – for example, that willpower is a mind-body response, not a virtue, and that it can be strengthened like a muscle.', 1],
    ['9780671027032', 'How to Win Friends and Influence People', null, 'Dale Carnegie', 'Simon & Schuster', 320, '15.99', '/covers/9780671027032.png', 'One of the best-known motivational guides in history, Dale Carnegie’s classic distils decades of experience into simple principles: make friends quickly and easily, win people to your way of thinking, and become a better speaker and a more entertaining conversationalist.', 1],
    ['9780735211292', 'Atomic Habits', 'An Easy & Proven Way to Build Good Habits & Break Bad Ones', 'James Clear', 'Avery', 320, '21.99', '/covers/9780735211292.png', 'No matter your goals, Atomic Habits offers a proven framework for improving every day. James Clear reveals practical strategies that will teach you how to form good habits, break bad ones, and master the tiny behaviours that lead to remarkable results.', 1],
    ['9780374533557', 'Thinking, Fast and Slow', null, 'Daniel Kahneman', 'Farrar, Straus and Giroux', 499, '20', '/covers/9780374533557.png', 'The Nobel laureate Daniel Kahneman takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think: System 1 is fast, intuitive and emotional; System 2 is slower, more deliberative and more logical. He exposes the faults and biases of fast thinking.', 1],
    ['9780062316097', 'Sapiens', 'A Brief History of Humankind', 'Yuval Noah Harari', 'Harper', 443, '24.99', '/covers/9780062316097.png', 'One hundred thousand years ago, at least six human species inhabited the earth. Today there is just one. Us. Sapiens explores how an unremarkable ape became the ruler of planet Earth – and asks what, if anything, we have learned from our tumultuous history.', 1],
    ['9781455586691', 'Deep Work', 'Rules for Focused Success in a Distracted World', 'Cal Newport', 'Grand Central Publishing', 296, '18.99', '/covers/9781455586691.png', 'Deep work is the ability to focus without distraction on a cognitively demanding task – a skill that allows you to master complicated information and produce better results in less time. Cal Newport argues it is becoming increasingly rare and increasingly valuable.', 1],
    ['9780061122415', 'The Alchemist', null, 'Paulo Coelho', 'HarperOne', 197, '16.99', '/covers/9780061122415.png', 'Santiago, an Andalusian shepherd boy, dreams of finding a worldly treasure and sets out on a journey to the Egyptian pyramids. Along the way he meets a gypsy woman, a man who calls himself king, and an alchemist, all of whom point him toward his own Personal Legend.', 1],
    ['9780451524935', '1984', 'Nineteen Eighty-Four', 'George Orwell', 'Signet Classics', 328, '9.99', '/covers/9780451524935.png', 'Winston Smith works for the Ministry of Truth in a nation ruled by the Party and its ever-watchful leader, Big Brother. Everything Winston does is monitored, thought is policed, and history is rewritten daily. Then he begins a forbidden diary – and a forbidden love affair.', 1],
    ['9780060850524', 'Brave New World', null, 'Aldous Huxley', 'Harper Perennial', 288, '15.99', '/covers/9780060850524.png', 'Far in the future, the World Controllers have created the ideal society: citizens are genetically engineered, conditioned from birth, and kept happy by the drug soma. Into this stable world comes a man raised outside it, and his presence forces everyone to confront what they have given up.', 1],
];

$stmt = $pdo->prepare(
    'INSERT INTO books (isbn, title, subtitle, author, publisher, num_pages, price, cover, abstract, user_id)
     VALUES (:isbn, :title, :subtitle, :author, :publisher, :num_pages, :price, :cover, :abstract, :user_id)'
);

foreach ($books as [$isbn, $title, $subtitle, $author, $publisher, $numPages, $price, $cover, $abstract, $userId]) {
    $stmt->execute([
        ':isbn' => $isbn,
        ':title' => $title,
        ':subtitle' => $subtitle,
        ':author' => $author,
        ':publisher' => $publisher,
        ':num_pages' => $numPages,
        ':price' => $price,
        ':cover' => $cover,
        ':abstract' => $abstract,
        ':user_id' => $userId,
    ]);
}

echo 'Seeded ' . count($books) . " books.\n";
